CREATE DATABASE IF NOT EXISTS bepet;
USE bepet;
DROP TABLE IF EXISTS mensagem;

CREATE TABLE mensagem (
    codigo BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    mensagem TEXT NOT NULL
);